### ISSUE TITLE
ReadMe: build instructions fail

### ISSUE THREAD

**Issue by janusw** [xabre/xamarin-bluetooth-le#492]
## Steps to reproduce

1. Look at https://github.com/xabre/xamarin-bluetooth-le/blob/master/README.md#how-to-build-the-nuget-package.

2. Follow the instructions.

3. A nupkg should tumble out.

## Expected behavior

The build should run through without errors.

## Actual behavior

The build instructions do not work. In particular, the file `build.bat` does not exist. It seems the build script has been ported to the cake build system.

### Crashlog

`no such file or directory: ./build.bat`

## Configuration

**Version of the Plugin:** e.g. 2.1.1

**Platform:** MacOS 11.2.3

**Device:** MacBook Pro

**Comment by smsissuechecker** [comment]
Hi @janusw,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by janusw** [comment]
Trying to build with cake v1.1.0 on MacOS results in:

```
% cd .build 
% cake 
The assembly 'Cake.Git, Version=0.21.0.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (0.33.0). 
For best compatibility it should target Cake.Core version 1.0.0.
The assembly 'Cake.FileHelpers, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (0.33.0). 
For best compatibility it should target Cake.Core version 1.0.0.
/Users/janus/github/xamarin-bluetooth-le/.build/build.cake(82,42): error CS1503: Argument 2: cannot convert from 'bool' to 'Cake.Common.IO.DeleteDirectorySettings'
Error: Error(s) occurred when compiling build script:
/Users/janus/github/xamarin-bluetooth-le/.build/build.cake(82,42): error CS1503: Argument 2: cannot convert from 'bool' to 'Cake.Common.IO.DeleteDirectorySettings'
```

**Comment by janusw** [comment]
The error above is fixed by this modification:

```diff
------------------------------ .build/build.cake ------------------------------
index fcf85ae..6328680 100644
@@ -79,7 +79,7 @@ Task("Build")
 Task("Clean").Does (() =>
 {
     if (DirectoryExists (BuildTargetDir))
-        DeleteDirectory (BuildTargetDir, true);
+        DeleteDirectory (BuildTargetDir, new DeleteDirectorySettings {Recursive = true});
 
     CleanDirectories ("./**/bin");
     CleanDirectories ("./**/obj");
```

**Comment by janusw** [comment]
Note: The class `DeleteDirectorySettings` has apparently been introduced in cake quite some time ago ...

* issue: https://github.com/cake-build/cake/issues/1564
* commit: https://github.com/cake-build/cake/commit/ba423697bf0f860428735ea59d68e562c342f112
* release: https://github.com/cake-build/cake/releases/tag/v0.22.0

**Comment by janusw** [comment]
After having a working cake build script, it turns out that also the `nuget pack` commands do not work any more (at least not on MacOS, where I tried it):

```
% nuget pack Plugin.BLE.nuspec -BasePath out/lib/         
Attempting to build package from 'Plugin.BLE.nuspec'.
Could not find a part of the path '/Users/janus/github/xamarin-bluetooth-le/.build/out/lib/out/lib/netstandard2.0'.

% nuget pack MvvmCross.Plugin.BLE.nuspec -BasePath out/lib/
Attempting to build package from 'MvvmCross.Plugin.BLE.nuspec'.
Could not find a part of the path '/Users/janus/github/xamarin-bluetooth-le/.build/out/lib/out/lib/mvx/netstandard2.0'.
```

The error message suggests that the BasePath is somehow duplicated, and consequently one can make the build work by leaving out the `-BasePath` argument:

```
% nuget pack Plugin.BLE.nuspec
% nuget pack MvvmCross.Plugin.BLE.nuspec
```

**Comment by janusw** [comment]
Even after managing to build a nupkg file, there is one remaining problem: When trying to update to the new package in an app that uses Plugin.BLE, I get the following error ...

```
Unable to find package Plugin.BLE.Abstractions. No packages exist with this id in source(s): nuget local packages, nuget.org
```

**Comment by janusw** [comment]
> Even after managing to build a nupkg file, there is one remaining problem: When trying to update to the new package in an app that uses Plugin.BLE, I get the following error ...
> 
> ```
> Unable to find package Plugin.BLE.Abstractions. No packages exist with this id in source(s): nuget local packages, nuget.org
> ```

Actually this error was apparently due to a problem with my local package cache, and could be fixed via:

`nuget locals all -clear`

Sorry for the noise :/

**Comment by janusw** [comment]
Fixed via #493.
